// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    IconHelper: typeof import('./components/IconHelper.vue')['default']
    LeagueSelector: typeof import('./components/dashboard/LeagueSelector.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    'Mdi:arrowRightThin': typeof import('~icons/mdi/arrow-right-thin')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ProcessButton: typeof import('./components/ProcessButton.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
  }
}

export { }
