// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    'Bx:bxLogOut': typeof import('~icons/bx/bx-log-out')['default']
    'Bx:bxsCalendarCheck': typeof import('~icons/bx/bxs-calendar-check')['default']
    'Bx:bxsCalendarPlus': typeof import('~icons/bx/bxs-calendar-plus')['default']
    'Fa:envelope': typeof import('~icons/fa/envelope')['default']
    'FileIcons:moleculer': typeof import('~icons/file-icons/moleculer')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'HeroiconsOutline:documentText': typeof import('~icons/heroicons-outline/document-text')['default']
    'HeroiconsOutline:exclamation': typeof import('~icons/heroicons-outline/exclamation')['default']
    'HeroiconsOutline:globe': typeof import('~icons/heroicons-outline/globe')['default']
    'HeroiconsOutline:home': typeof import('~icons/heroicons-outline/home')['default']
    'HeroiconsOutline:menuAlt1': typeof import('~icons/heroicons-outline/menu-alt1')['default']
    'HeroiconsOutline:shieldCheck': typeof import('~icons/heroicons-outline/shield-check')['default']
    'HeroiconsOutline:speakerphone': typeof import('~icons/heroicons-outline/speakerphone')['default']
    'HeroiconsOutline:x': typeof import('~icons/heroicons-outline/x')['default']
    HeroiconsOutlineMenu: typeof import('~icons/heroicons-outline/menu')['default']
    HeroiconsOutlineMoon: typeof import('~icons/heroicons-outline/moon')['default']
    HeroiconsOutlineSun: typeof import('~icons/heroicons-outline/sun')['default']
    'HeroiconsSolid:check': typeof import('~icons/heroicons-solid/check')['default']
    'HeroiconsSolid:chevronDown': typeof import('~icons/heroicons-solid/chevron-down')['default']
    'HeroiconsSolid:filter': typeof import('~icons/heroicons-solid/filter')['default']
    'Ic:baselineDiscord': typeof import('~icons/ic/baseline-discord')['default']
    'Ic:sharpDashboard': typeof import('~icons/ic/sharp-dashboard')['default']
    'Iconoir:notes': typeof import('~icons/iconoir/notes')['default']
    'Ion:iosPeople': typeof import('~icons/ion/ios-people')['default']
    'Iwwa:year': typeof import('~icons/iwwa/year')['default']
    LeagueSelector: typeof import('./components/dashboard/LeagueSelector.vue')['default']
    'Mdi:arrowRightThin': typeof import('~icons/mdi/arrow-right-thin')['default']
    'Mdi:discord': typeof import('~icons/mdi/discord')['default']
    'Mdi:notebookCheck': typeof import('~icons/mdi/notebook-check')['default']
    'Mdi:patreon': typeof import('~icons/mdi/patreon')['default']
    'Mdi:twitter': typeof import('~icons/mdi/twitter')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    'Ph:calendarXFill': typeof import('~icons/ph/calendar-x-fill')['default']
    'Ph:hashBold': typeof import('~icons/ph/hash-bold')['default']
    ProcessButton: typeof import('./components/ProcessButton.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    'Subway:admin': typeof import('~icons/subway/admin')['default']
    'Whh:website': typeof import('~icons/whh/website')['default']
  }
}

export { }
