name: Publish Website

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build request
        run: curl -X POST -d {} {{ secrets.BUILD_HOOK }}
