name: Lint Test
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install NPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm ci

      - name: Run ESLint
        run: pnpm run lint

  build:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install NPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm ci

      - name: Run site build
        run: pnpm run build
